### ISSUE TITLE
Small things to fix:

### ISSUE THREAD

**Issue by mjhmilla** [ORB-HD/rbdl-toolkit#3]
1. Insert this line in the CMakeLists.txt file before the block of FIND_PACKAGE statements:

SET(CUSTOM_RBDL_PATH "" CACHE PATH "Path to specific RBDL Installation")

2. In the Toolkit->File menu I see two entries for 'Load Animation'

3. The arrow keys no longer move the camera position. If this is quick and easy to add, consider doing so.

4. With the mouse I can rotate, and I can pan. I don't know how to zoom, or walk forwards. How do I do this? 

5. It's nice to have the option of seeing a solid floor. Though I suppose I can add this in the Lua file, so never mind!

**Comment by ju6ge** [comment]
1. is an easy fix and will be added with the next commit

2. this is something that happens when plugin librarys are located at multiple locations, that are searched so I will think of some logic to prevent double loading.

3. and 
4. I am using the movement definitions of the QOribitCameraController:
https://doc.qt.io/qt-5/qt3dextras-qorbitcameracontroller.html#details
If they do not work try clicking on the rendering display.

5. I am planning on adding more options to be displayed.

**Comment by ju6ge** [comment]
020a9be1eb55e53dc71bfba77f26a906ed39baf9
